### ISSUE TITLE
php 7.2 Object.php reserved

### ISSUE THREAD

**Issue by spritian** [ionux/phactor#11]
Just FYI, I had to rename file and change references to Object in order for it to work in php 7.2. 

I was getting the following error:
Cannot use 'Object' as class name as it is reserved

Thanks

**Comment by TiMESPLiNTER** [comment]
master branch should be compatible with php 7.2, there's just no new release so far. So if you depend on `dev-master` you don't have to apply the changes anymore.

**Comment by ionux** [comment]
@spritian @TiMESPLiNTER I just released v1.0.8 which bundle these fixes into an official release.  Thank you both for your help and contributions!
