### ISSUE TITLE
Load Pkcs cert

### ISSUE THREAD

**Issue by own2pwn** [ionux/phactor#3]
Hey, can I load Pkcs7 or Pkcs12 formatted private key?

**Comment by ionux** [comment]
I'll add this in a future release @own2pwn .  Appreciate the feature request!

**Comment by adoley** [comment]
Hi,
Is loading of Pkcs8 format private key is supported ?

**Comment by ionux** [comment]
No, not yet.  Only public key formats are supported at this time.  I'm going to be working on this for a future release, however.
