### ISSUE TITLE
PHP 7.2 issues

### ISSUE THREAD

**Issue by burstpay** [ionux/phactor#7]
Hello

Under php 7.2 i'm getting the following:
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/vendor/ionux/phactor/src/Object.php on line 35

Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/vendor/ionux/phactor/src/Object.php on line 35

Thanks

**Comment by TiMESPLiNTER** [comment]
@ionux @burstpay I created a PR to make the lib compatible with PHP 7.2

**Comment by ionux** [comment]
@burstpay @TiMESPLiNTER Thank you guys for bringing this up and thanks Timesplinter for the PRs!
